name: "Test"
on:
  push:

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    container: ghcr.io/sensoris/faiss-base-image:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Cargo check
        run: cargo check --all-features
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Run tests
        run: cargo test --all-features -- --nocapture
        env:
          LD_LIBRARY_PATH: "/usr/local/lib"
