name: "Test"
on:
  push:
    paths-ignore:
      - 'docs/**'

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  unit-test:
    name: Lint & Unit Test
    runs-on: ubuntu-latest
    container: ghcr.io/sensoris/faiss-base-image:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set default Rust toolchain
        run: rustup default stable
      - name: Cargo format check
        run: cargo fmt --check
      - name: Run unit tests
        run: cargo test --bins -- --nocapture
        env:
          LD_LIBRARY_PATH: "/usr/local/lib"

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: unit-test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Set default Rust toolchain
        run: rustup default stable
      - name: Build semcache container
        run: docker build -f docker/Dockerfile -t semcache .
      - name: Run integration tests
        run: cargo test --tests -- --nocapture
