name: "Test"
on:
  push:

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  test:
    name: Lint & Test
    runs-on: large-runner
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.81.0
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Cargo check
        run: cargo check --all-features
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Run tests
        run: cargo test --all-features
