name: "Test"
on:
  push:

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      #- uses: Swatinem/rust-cache@v2
      #- name: Cargo check
      #  run: cargo check --all-features
      #- name: Rustfmt Check
      #  uses: actions-rust-lang/rustfmt@v1
      # Run tests using Docker
      - name: Get latest FAISS commit for use in the docker cache hash
        id: faiss
        run: |
          echo "sha=$(git ls-remote https://github.com/facebookresearch/faiss.git HEAD | cut -f1)" >> "$GITHUB_OUTPUT"

      - name: Cache faiss build container
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-faiss-${{ steps.faiss.outputs.sha }}-${{ hashFiles('Dockerfile.faiss') }}
          restore-keys: |
            buildx-faiss-
      - name: Build faiss-base-image with caching
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.faiss
          tags: faiss-base-image
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build test image using builder
        run: docker build -f Dockerfile.test -t semcache-test .

      - name: Run tests inside test container
        run: docker run -t --rm semcache-test
